# Конфигурации по продуктам
products:
  fitnesscorp:
    product_name: "Fitness_CORP"
    serie: "5415"
    rel_repository: "http://192.168.2.16/hran1c/repository.1ccr/fitness_release"
    repository_user: "VATest"
    release_server: "VAFitness"
    release_user: "Админ"
    base_build: "localhost/FitnessCorpSborka"
    base_name_inf: "FitnessCorpSborka"
    build_user: "Администратор БД"
    source_directory: "C:\\automation\\sample\\Fitness"
    sample_edf: "C:\\automation\\sample\\edf\\FitnessCorp"
    extension_name_mess: "Мессенджер"
    edf_name_full: "Комплект поставки.edf"
    edf_name_obnov: "Файл описания комплекта поставки.edf"
    name_distr: "Fitness"
    target_path: "D:\\Release_build\\FITNESSCORP\\Fitness"
    collected_release_p: "D:\\Release_build\\FITNESSCORP\\Collected_release\\Polnaya"
    collected_release_ob: "D:\\Release_build\\FITNESSCORP\\Collected_release\\obnovlenine"
    old_cf: "D:\\Release_build\\FITNESSCORP\\Old_versions_cf"
    fbrb: "D:\\Release_build\\FITNESSCORP\\files_before_release_build"
    sbor: "D:\\Release_build\\FITNESSCORP\\Sbor"
    netlenka: "D:\\Release_build\\FITNESSCORP\\Netlenka1c"
    archive_name: "D:\\Release_build\\FITNESSCORP"
    

  stoma:
    product_name: "Stomatology"
    rel_repository: "http://192.168.2.16/hran1c/repository.1ccr/stomatology2_release"
    repository_user: "VATest"
    release_server: "VAStoma"
    release_user: "Админ"
    base_build: "localhost/StomaSborka"
    base_name_inf: "StomaSborka"
    build_user: "Николаев Лев (Полные права)"
    source_directory: "C:\\automation\\sample\\Stomatology"
    sample_edf: "C:\\automation\\sample\\edf\\Stomatology"
    extension_name_mess: "Мессенджер_Стоматология"
    extension_name_jurnal: "ЖурналЗаписи_Стоматология"
    edf_name_full: "1С_Медицина_21_Внутренний_КомплектПоставки.edf"
    edf_name_obnov: "Файл описания комплекта поставки.edf"
    name_distr: "Стоматологическая клиника"
    target_path: "D:\\Release_build\\STOMA\\Stomatology"
    collected_release_p: "D:\\Release_build\\STOMA\\Collected_release\\Polnaya"
    collected_release_ob: "D:\\Release_build\\STOMA\\Collected_release\\obnovlenine"
    old_cf: "D:\\Release_build\\STOMA\\Old_versions_cf"
    fbrb: "D:\\Release_build\\STOMA\\files_before_release_build"
    sbor: "D:\\Release_build\\STOMA\\Sbor"
    netlenka: "D:\\Release_build\\STOMA\\Netlenka1c"
    archive_name: "D:\\Release_build\\STOMA"